[package]
name = "futures"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["futures", "async", "future"]
repository = "https://github.com/alexcrichton/futures-rs"
homepage = "https://github.com/alexcrichton/futures-rs"
documentation = "http://alexcrichton.com/futures-rs/futures/"
description = """
An implementation of futures and streams featuring zero allocations,
composability, and iterator-like interfaces.
"""

[workspace]
members = [
  "futures-tls",
  "futures-io",
  "futures-mio",
  "futures-iobuf",
  "futures-cpupool",
  "futures-minihttp",
  "futures-minihttp/tls-example",
  "futures-minihttp/techempower1",
  "futures-minihttp/techempower2",
  "futures-socks5",
  "futures-curl",
  "futures-uds",
  "futures-dns"
]

[dependencies]
log = { version = "0.3", default-features = true }
scoped-tls = { version = "0.1", optional = true }

[features]
use_std = ["scoped-tls"]
default = ["use_std"]
